import json
import os
import re
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from google import genai
from pydantic import BaseModel
from pypdf import PdfReader
from docx import Document


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
ENV_FILE = BASE_DIR / ".env"

load_dotenv(dotenv_path=ENV_FILE)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


# ============================================================
# GEMINI CLIENT
# ============================================================

if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY is not configured. "
        "Please add it to backend/.env"
    )

client = genai.Client(
    api_key=GEMINI_API_KEY
)


# ============================================================
# FASTAPI APP
# ============================================================

app = FastAPI(
    title="AI StudyMind Generator API",
    description=(
        "Generate summaries, preparation guides, flashcards, "
        "interview questions, and quizzes from study material "
        "using Google Gemini."
    ),
    version="2.0.0",
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# GEMINI CONFIGURATION
# ============================================================

GEMINI_MODEL = "gemini-2.5-flash"

MAX_WORDS = 3000

ALLOWED_EXTENSIONS = {
    ".pdf",
    ".docx",
    ".txt",
}


# ============================================================
# REQUEST MODEL
# ============================================================

class GenerateRequest(BaseModel):
    notes: str


# ============================================================
# CLEAN GEMINI RESPONSE
# ============================================================

def clean_json_response(response_text: str) -> str:
    """
    Remove Markdown code fences if Gemini returns JSON
    inside ```json ... ``` blocks.
    """

    response_text = response_text.strip()

    response_text = re.sub(
        r"^```json\s*",
        "",
        response_text,
        flags=re.IGNORECASE,
    )

    response_text = re.sub(
        r"^```\s*",
        "",
        response_text,
    )

    response_text = re.sub(
        r"\s*```$",
        "",
        response_text,
    )

    return response_text.strip()


# ============================================================
# EXTRACT JSON OBJECT FROM RESPONSE
# ============================================================

def extract_json_object(text: str) -> str:
    """
    Extract the JSON object from Gemini's response.

    This provides extra protection in case Gemini returns
    a small amount of text before or after the JSON.
    """

    text = text.strip()

    first_brace = text.find("{")
    last_brace = text.rfind("}")

    if first_brace == -1 or last_brace == -1:
        raise ValueError(
            "No valid JSON object found in Gemini response."
        )

    return text[first_brace:last_brace + 1]


# ============================================================
# VALIDATE GENERATED DATA
# ============================================================

def validate_generated_data(data: dict) -> dict:
    """
    Validate the complete structure generated by Gemini.
    """

    required_top_level_fields = [
        "summary",
        "preparationGuide",
        "flashcards",
        "interviewQuestions",
        "quiz",
    ]

    for field in required_top_level_fields:

        if field not in data:
            raise ValueError(
                f"Gemini response is missing '{field}'."
            )

    # ========================================================
    # SUMMARY
    # ========================================================

    if not isinstance(
        data["summary"],
        str,
    ):
        raise ValueError(
            "'summary' must be a string."
        )

    if not data["summary"].strip():
        raise ValueError(
            "'summary' cannot be empty."
        )

    # ========================================================
    # PREPARATION GUIDE
    # ========================================================

    preparation_guide = data[
        "preparationGuide"
    ]

    if not isinstance(
        preparation_guide,
        list,
    ):
        raise ValueError(
            "'preparationGuide' must be a list."
        )

    if len(preparation_guide) < 5:
        raise ValueError(
            "Preparation guide must contain "
            "at least 5 steps."
        )

    for index, item in enumerate(
        preparation_guide,
        start=1,
    ):

        if not isinstance(item, dict):
            raise ValueError(
                f"Preparation guide item {index} "
                "must be an object."
            )

        required_fields = [
            "step",
            "title",
            "description",
            "priority",
        ]

        for field in required_fields:

            if field not in item:
                raise ValueError(
                    f"Preparation guide item {index} "
                    f"is missing '{field}'."
                )

    # ========================================================
    # FLASHCARDS
    # ========================================================

    flashcards = data["flashcards"]

    if not isinstance(
        flashcards,
        list,
    ):
        raise ValueError(
            "'flashcards' must be a list."
        )

    if len(flashcards) < 10:
        raise ValueError(
            "At least 10 flashcards are required."
        )

    for index, card in enumerate(
        flashcards,
        start=1,
    ):

        if not isinstance(card, dict):
            raise ValueError(
                f"Flashcard {index} "
                "must be an object."
            )

        required_fields = [
            "id",
            "question",
            "answer",
        ]

        for field in required_fields:

            if field not in card:
                raise ValueError(
                    f"Flashcard {index} "
                    f"is missing '{field}'."
                )

    # ========================================================
    # INTERVIEW QUESTIONS
    # ========================================================

    interview_questions = data[
        "interviewQuestions"
    ]

    if not isinstance(
        interview_questions,
        list,
    ):
        raise ValueError(
            "'interviewQuestions' must be a list."
        )

    if len(interview_questions) < 10:
        raise ValueError(
            "At least 10 interview questions "
            "are required."
        )

    for index, question in enumerate(
        interview_questions,
        start=1,
    ):

        if not isinstance(
            question,
            dict,
        ):
            raise ValueError(
                f"Interview question {index} "
                "must be an object."
            )

        required_fields = [
            "id",
            "difficulty",
            "question",
            "answer",
            "keyPoints",
        ]

        for field in required_fields:

            if field not in question:
                raise ValueError(
                    f"Interview question {index} "
                    f"is missing '{field}'."
                )

        if not isinstance(
            question["keyPoints"],
            list,
        ):
            raise ValueError(
                f"Interview question {index} "
                "'keyPoints' must be a list."
            )

    # ========================================================
    # QUIZ
    # ========================================================

    quiz = data["quiz"]

    if not isinstance(
        quiz,
        list,
    ):
        raise ValueError(
            "'quiz' must be a list."
        )

    if len(quiz) < 10:
        raise ValueError(
            "At least 10 quiz questions "
            "are required."
        )

    for index, question in enumerate(
        quiz,
        start=1,
    ):

        if not isinstance(
            question,
            dict,
        ):
            raise ValueError(
                f"Quiz question {index} "
                "must be an object."
            )

        required_fields = [
            "id",
            "difficulty",
            "question",
            "options",
            "correctAnswerIndex",
            "explanation",
        ]

        for field in required_fields:

            if field not in question:
                raise ValueError(
                    f"Quiz question {index} "
                    f"is missing '{field}'."
                )

        # Validate difficulty

        difficulty = question[
            "difficulty"
        ].lower()

        if difficulty not in [
            "easy",
            "medium",
            "hard",
        ]:
            raise ValueError(
                f"Quiz question {index} "
                f"has invalid difficulty."
            )

        # Validate options

        options = question[
            "options"
        ]

        if not isinstance(
            options,
            list,
        ):
            raise ValueError(
                f"Quiz question {index} "
                "'options' must be a list."
            )

        if len(options) != 4:
            raise ValueError(
                f"Quiz question {index} "
                "must have exactly 4 options."
            )

        # Validate correct answer

        correct_index = question[
            "correctAnswerIndex"
        ]

        if not isinstance(
            correct_index,
            int,
        ):
            raise ValueError(
                f"Quiz question {index} "
                "'correctAnswerIndex' must "
                "be an integer."
            )

        if correct_index < 0 or correct_index > 3:
            raise ValueError(
                f"Quiz question {index} "
                "'correctAnswerIndex' must "
                "be between 0 and 3."
            )

    return data


# ============================================================
# BUILD GEMINI PROMPT
# ============================================================

def build_prompt(notes: str) -> str:

    return f"""
You are an expert AI study assistant.

Your job is to create a complete and useful study
workspace from the student's provided study material.

IMPORTANT SOURCE RULE:

Use the provided study material as the primary source.

Do NOT assume the topic is Machine Learning.

Do NOT generate generic Machine Learning content unless
Machine Learning is actually present in the provided
study material.

If the user provides content about Python, Java, SQL,
Cloud Computing, Networking, Data Structures, Aptitude,
Physics, Mathematics, History, Biology, or any other topic,
generate content specifically about that topic.

The generated content must be relevant to the actual
provided material.

Do not replace the user's content with a default topic.

============================================================
TASK 1: SUMMARY
============================================================

Create a detailed study summary.

The summary should:

- Explain the main topic clearly.
- Cover the most important concepts.
- Include important definitions.
- Include important relationships or processes.
- Mention important examples from the notes when available.
- Be useful for exam preparation.
- Be detailed enough for a student to revise from.

Do not make the summary unnecessarily short.

============================================================
TASK 2: PREPARATION GUIDE
============================================================

Create at least 8 preparation steps.

Each step must contain:

- step
- title
- description
- priority

Priority should be one of:

- High Priority
- Medium Priority
- Low Priority

The preparation guide should be specific to the
provided study material.

============================================================
TASK 3: FLASHCARDS
============================================================

Generate exactly 10 flashcards.

Each flashcard must contain:

- id
- question
- answer

Rules:

- Focus on important concepts.
- Use detailed but easy-to-understand answers.
- Avoid unnecessary repetition.
- Cover different parts of the study material.
- Questions should help with revision.
- Answers should contain enough information to understand
  the concept properly.

============================================================
TASK 4: INTERVIEW QUESTIONS AND ANSWERS
============================================================

Generate exactly 10 technical interview questions.

Each question must contain:

- id
- difficulty
- question
- answer
- keyPoints

Difficulty can be:

- Basic
- Intermediate
- Advanced

The answers should be detailed and interview-ready.

Include:

- Conceptual questions.
- Comparison questions where relevant.
- Practical or scenario-based questions where relevant.
- Important technical questions related to the material.

keyPoints must contain 2 to 5 important points.

If the provided material is not technical, generate
appropriate subject-related viva or interview-style
questions instead.

============================================================
TASK 5: PRACTICE QUIZ
============================================================

Generate exactly 10 multiple-choice questions.

Each question must contain:

- id
- difficulty
- question
- options
- correctAnswerIndex
- explanation

Difficulty must be:

- easy
- medium
- hard

Each question must have exactly 4 options.

Only one option can be correct.

correctAnswerIndex must be:

0, 1, 2, or 3

The explanation must explain why the correct answer
is correct.

Questions must be based on the provided material.

============================================================
IMPORTANT OUTPUT RULES
============================================================

Return ONLY valid JSON.

Do not return:

- Markdown
- ```json
- Code fences
- Introduction
- Explanation outside JSON
- Text before JSON
- Text after JSON

Return exactly this structure:

{{
  "summary": "Detailed summary here",

  "preparationGuide": [
    {{
      "step": 1,
      "title": "Step title",
      "description": "Detailed preparation step",
      "priority": "High Priority"
    }}
  ],

  "flashcards": [
    {{
      "id": 1,
      "question": "Question here",
      "answer": "Detailed answer here"
    }}
  ],

  "interviewQuestions": [
    {{
      "id": 1,
      "difficulty": "Basic",
      "question": "Interview question here",
      "answer": "Detailed interview answer here",
      "keyPoints": [
        "Important point 1",
        "Important point 2"
      ]
    }}
  ],

  "quiz": [
    {{
      "id": 1,
      "difficulty": "easy",
      "question": "Quiz question here",
      "options": [
        "Option A",
        "Option B",
        "Option C",
        "Option D"
      ],
      "correctAnswerIndex": 0,
      "explanation": "Explanation here"
    }}
  ]
}}

============================================================
STUDY MATERIAL
============================================================

{notes}
"""


# ============================================================
# GENERATE STUDY MATERIAL USING GEMINI
# ============================================================

def generate_from_notes(notes: str) -> dict:

    notes = notes.strip()

    if not notes:
        raise HTTPException(
            status_code=400,
            detail=(
                "Study material cannot be empty."
            ),
        )

    word_count = len(
        notes.split()
    )

    if word_count < 10:
        raise HTTPException(
            status_code=400,
            detail=(
                "Please provide at least "
                "10 words of study material."
            ),
        )

    if word_count > MAX_WORDS:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Study material cannot exceed "
                f"{MAX_WORDS} words."
            ),
        )

    prompt = build_prompt(
        notes
    )

    # ========================================================
    # CALL GEMINI
    # ========================================================

    try:

        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
        )

    except Exception as e:

        print(
            "Gemini API error:",
            repr(e),
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "Failed to generate study material "
                "using Gemini. Please check your "
                "API key, model availability, "
                "and API quota."
            ),
        )

    # ========================================================
    # EXTRACT RESPONSE
    # ========================================================

    try:

        ai_text = response.text

        if not ai_text:
            raise ValueError(
                "Gemini returned an empty response."
            )

        ai_text = clean_json_response(
            ai_text
        )

        ai_text = extract_json_object(
            ai_text
        )

    except Exception as e:

        print(
            "Gemini response extraction error:",
            repr(e),
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "Gemini returned an empty or "
                "invalid response."
            ),
        )

    # ========================================================
    # PARSE JSON
    # ========================================================

    try:

        generated_data = json.loads(
            ai_text
        )

    except json.JSONDecodeError as e:

        print(
            "JSON parsing error:",
            repr(e),
        )

        print(
            "Raw Gemini response:",
            ai_text,
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "Gemini returned invalid JSON. "
                "Please try again."
            ),
        )

    # ========================================================
    # VALIDATE DATA
    # ========================================================

    try:

        generated_data = validate_generated_data(
            generated_data
        )

    except ValueError as e:

        print(
            "Generated data validation error:",
            repr(e),
        )

        raise HTTPException(
            status_code=500,
            detail=str(e),
        )

    # ========================================================
    # RETURN RESPONSE
    # ========================================================

    return {
        "message": (
            "Study material generated successfully."
        ),
        "word_count": word_count,
        "summary": generated_data[
            "summary"
        ],
        "preparationGuide": generated_data[
            "preparationGuide"
        ],
        "flashcards": generated_data[
            "flashcards"
        ],
        "interviewQuestions": generated_data[
            "interviewQuestions"
        ],
        "quiz": generated_data[
            "quiz"
        ],
    }


# ============================================================
# EXTRACT TEXT FROM PDF
# ============================================================

def extract_pdf_text(
    file_bytes: bytes,
) -> str:

    import io

    pdf_stream = io.BytesIO(
        file_bytes
    )

    reader = PdfReader(
        pdf_stream
    )

    pages_text = []

    for page in reader.pages:

        text = page.extract_text()

        if text:
            pages_text.append(
                text
            )

    return "\n".join(
        pages_text
    ).strip()


# ============================================================
# EXTRACT TEXT FROM DOCX
# ============================================================

def extract_docx_text(
    file_bytes: bytes,
) -> str:

    import io

    doc_stream = io.BytesIO(
        file_bytes
    )

    document = Document(
        doc_stream
    )

    paragraphs = []

    for paragraph in document.paragraphs:

        text = paragraph.text.strip()

        if text:
            paragraphs.append(
                text
            )

    # Also extract table content

    for table in document.tables:

        for row in table.rows:

            row_text = []

            for cell in row.cells:

                cell_text = (
                    cell.text.strip()
                )

                if cell_text:
                    row_text.append(
                        cell_text
                    )

            if row_text:

                paragraphs.append(
                    " | ".join(
                        row_text
                    )
                )

    return "\n".join(
        paragraphs
    ).strip()


# ============================================================
# EXTRACT TEXT FROM TXT
# ============================================================

def extract_txt_text(
    file_bytes: bytes,
) -> str:

    try:

        return file_bytes.decode(
            "utf-8"
        ).strip()

    except UnicodeDecodeError:

        return file_bytes.decode(
            "latin-1"
        ).strip()


# ============================================================
# EXTRACT TEXT FROM UPLOADED FILE
# ============================================================

def extract_file_text(
    filename: str,
    file_bytes: bytes,
) -> str:

    extension = Path(
        filename
    ).suffix.lower()

    if extension == ".pdf":

        return extract_pdf_text(
            file_bytes
        )

    if extension == ".docx":

        return extract_docx_text(
            file_bytes
        )

    if extension == ".txt":

        return extract_txt_text(
            file_bytes
        )

    raise HTTPException(
        status_code=400,
        detail=(
            "Unsupported file type. "
            "Please upload PDF, DOCX, or TXT."
        ),
    )


# ============================================================
# ROOT ENDPOINT
# ============================================================

@app.get("/")
def root():

    return {
        "message": (
            "AI StudyMind Generator API "
            "is running."
        ),
        "ai_provider": "Google Gemini",
        "model": GEMINI_MODEL,
        "endpoints": [
            "/api/generate",
            "/api/generate-file",
        ],
    }


# ============================================================
# TEXT GENERATION ENDPOINT
# ============================================================

@app.post(
    "/api/generate"
)
def generate_study_material(
    request: GenerateRequest,
):

    return generate_from_notes(
        request.notes
    )


# ============================================================
# FILE UPLOAD GENERATION ENDPOINT
# ============================================================

@app.post(
    "/api/generate-file"
)
async def generate_from_file(
    file: UploadFile = File(...),
):

    # ========================================================
    # VALIDATE FILE NAME
    # ========================================================

    if not file.filename:

        raise HTTPException(
            status_code=400,
            detail=(
                "Uploaded file must have a filename."
            ),
        )

    extension = Path(
        file.filename
    ).suffix.lower()

    if extension not in ALLOWED_EXTENSIONS:

        raise HTTPException(
            status_code=400,
            detail=(
                "Unsupported file type. "
                "Please upload PDF, DOCX, or TXT."
            ),
        )

    # ========================================================
    # READ FILE
    # ========================================================

    try:

        file_bytes = await file.read()

    except Exception as e:

        print(
            "File reading error:",
            repr(e),
        )

        raise HTTPException(
            status_code=400,
            detail=(
                "Could not read the uploaded file."
            ),
        )

    # ========================================================
    # CHECK FILE SIZE
    # ========================================================

    max_file_size = (
        10 * 1024 * 1024
    )

    if len(file_bytes) > max_file_size:

        raise HTTPException(
            status_code=400,
            detail=(
                "File size must be less than "
                "10 MB."
            ),
        )

    if len(file_bytes) == 0:

        raise HTTPException(
            status_code=400,
            detail=(
                "Uploaded file is empty."
            ),
        )

    # ========================================================
    # EXTRACT TEXT
    # ========================================================

    try:

        extracted_text = extract_file_text(
            file.filename,
            file_bytes,
        )

    except HTTPException:

        raise

    except Exception as e:

        print(
            "Text extraction error:",
            repr(e),
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "Failed to extract text from "
                "the uploaded file."
            ),
        )

    # ========================================================
    # VALIDATE EXTRACTED TEXT
    # ========================================================

    if not extracted_text.strip():

        raise HTTPException(
            status_code=400,
            detail=(
                "Could not extract readable text "
                "from the uploaded file."
            ),
        )

    # ========================================================
    # LIMIT WORD COUNT
    # ========================================================

    words = extracted_text.split()

    if len(words) > MAX_WORDS:

        extracted_text = " ".join(
            words[:MAX_WORDS]
        )

    # ========================================================
    # GENERATE AI CONTENT
    # ========================================================

    result = generate_from_notes(
        extracted_text
    )

    # ========================================================
    # ADD FILE INFORMATION
    # ========================================================

    result["source"] = {
        "type": "file",
        "filename": file.filename,
        "extension": extension,
    }

    return result